#
# Jekyll
#
name: there4.co
timezone: Europe/Madrid
encoding: UTF-8

future: false
permalink: pretty

markdown: kramdown

#
# Custom
#

# Third party services
analytics:
  id: UA-48216810-1
  property: there4.co
disqus_shortname: there4co

bootstrapcdn: http://netdna.bootstrapcdn.com
cloudflare: http://cdnjs.cloudflare.com/ajax/libs
googlefonts: http://fonts.googleapis.com/css?family

# Site
title: I Think<br/>Therefore<br/>I Code
tagline: (The opposite is not always true)

production_url: http://there4.co

# Author
author:
  name: Juan José Aguililla
  github: jamming
  twitter: jaguililla
  linkedin: jaguililla
  email: juanjoaguililla@gmail.com

